// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Restaurant_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024140303_AddInventory")]
    partial class AddInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoryname");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.HasKey("CategoryID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CustomizationOption", b =>
                {
                    b.Property<int>("CustomizationOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customizationoptionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomizationOptionID"));

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("fixedprice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("CustomizationOptionID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("customizationoptions", (string)null);
                });

            modelBuilder.Entity("KitchenNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("isacknowledged");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("notificationtime");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("TableNo")
                        .HasColumnType("integer")
                        .HasColumnName("tableno");

                    b.HasKey("NotificationId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RestaurantID");

                    b.ToTable("kitchennotifications", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventoryitemid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryItemID"));

                    b.Property<decimal>("AverageUnitCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("averageunitcost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("currentquantity");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("itemname");

                    b.Property<decimal>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("reorderlevel");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unitofmeasure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("InventoryItemID");

                    b.HasIndex("RestaurantID", "ItemName")
                        .IsUnique();

                    b.HasIndex("RestaurantID", "SKU");

                    b.ToTable("inventoryitems", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Offer", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferID"));

                    b.Property<bool>("AutoApply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<float?>("DiscountPercent")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MinBillAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OfferID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<int?>("AppliedOfferID")
                        .HasColumnType("integer")
                        .HasColumnName("appliedofferid");

                    b.Property<decimal>("CGST")
                        .HasColumnType("numeric")
                        .HasColumnName("cgst");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closedat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discountamount");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("isassigned");

                    b.Property<int?>("KitchenStatus")
                        .HasColumnType("integer")
                        .HasColumnName("kitchenstatus");

                    b.Property<DateTime?>("LastKitchenReadyAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lastkitchenreadyat");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("orderstatus");

                    b.Property<bool>("PlaySound")
                        .HasColumnType("boolean")
                        .HasColumnName("playsound");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int?>("RestaurantTableID")
                        .HasColumnType("integer")
                        .HasColumnName("restauranttableid");

                    b.Property<decimal>("SGST")
                        .HasColumnType("numeric")
                        .HasColumnName("sgst");

                    b.Property<decimal>("ServiceCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("servicecharge");

                    b.Property<int?>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalamount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int?>("WaiterUserID")
                        .HasColumnType("integer")
                        .HasColumnName("waiteruserid");

                    b.HasKey("OrderID");

                    b.HasIndex("AppliedOfferID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("RestaurantTableID");

                    b.HasIndex("WaiterUserID");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderChangeHistory", b =>
                {
                    b.Property<int>("OrderChangeHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderchangehistoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderChangeHistoryID"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("changetype");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedat");

                    b.Property<int?>("ChangedByUserID")
                        .HasColumnType("integer")
                        .HasColumnName("changedbyuserid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("newvalues");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oldvalues");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("OrderChangeHistoryID");

                    b.HasIndex("ChangedByUserID");

                    b.HasIndex("OrderID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("orderchangehistory", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderitemid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemID"));

                    b.Property<DateTime>("AddedToKitchenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("addedtokitchenat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("batchid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsPrepared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isprepared");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<DateTime?>("PreparedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("preparedat");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitprice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("orderitems", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderItemCustomization", b =>
                {
                    b.Property<int>("OrderItemCustomizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderitemcustomizationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemCustomizationID"));

                    b.Property<int>("CustomizationOptionID")
                        .HasColumnType("integer")
                        .HasColumnName("customizationoptionid");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("integer")
                        .HasColumnName("orderitemid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("OrderItemCustomizationID");

                    b.HasIndex("CustomizationOptionID");

                    b.HasIndex("OrderItemID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("orderitemcustomizations", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completedat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("boolean")
                        .HasColumnName("isnotified");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("PaymentChannel")
                        .HasColumnType("integer")
                        .HasColumnName("paymentchannel");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentstatus");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("TableNo")
                        .HasColumnType("integer")
                        .HasColumnName("tableno");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("imagepath");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("isavailable");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("boolean")
                        .HasColumnName("isveg");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text")
                        .HasColumnName("productdescription");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int?>("SubCategoryID")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoryid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.ProductRecipe", b =>
                {
                    b.Property<int>("ProductRecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productrecipeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductRecipeID"));

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("integer")
                        .HasColumnName("inventoryitemid");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantityperunit");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("ProductRecipeID");

                    b.HasIndex("InventoryItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RestaurantID", "ProductID", "InventoryItemID")
                        .IsUnique();

                    b.ToTable("productrecipes", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RestaurantID"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logopath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("UPI_ID")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("upi_id");

                    b.Property<string>("UPI_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("upi_name");

                    b.HasKey("RestaurantID");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.RestaurantTable", b =>
                {
                    b.Property<int>("RestaurantTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("restauranttableid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RestaurantTableID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("tablename");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("RestaurantTableID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("restauranttables", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reviewid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("ReviewID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.StockTransaction", b =>
                {
                    b.Property<int>("StockTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stocktransactionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockTransactionID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("integer")
                        .HasColumnName("inventoryitemid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantitychange");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("transactiontime");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transactiontype");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitcost");

                    b.HasKey("StockTransactionID");

                    b.HasIndex("InventoryItemID");

                    b.HasIndex("RestaurantID", "InventoryItemID", "TransactionTime");

                    b.ToTable("stocktransactions", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subcategoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subcategoryname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("isavailable");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userrole");

                    b.HasKey("UserID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.WaiterNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("isacknowledged");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("TableNo")
                        .HasColumnType("integer")
                        .HasColumnName("tableno");

                    b.HasKey("NotificationId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RestaurantID");

                    b.ToTable("waiternotifications", (string)null);
                });

            modelBuilder.Entity("Restaurant_Menu.Models.WaiterRequest", b =>
                {
                    b.Property<int>("WaiterRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("waiterrequestid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WaiterRequestID"));

                    b.Property<bool>("IsNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isnotified");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("message");

                    b.Property<DateTime>("RequestTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("requesttime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("RestaurantTableID")
                        .HasColumnType("integer")
                        .HasColumnName("restauranttableid");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("tablenumber");

                    b.HasKey("WaiterRequestID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("RestaurantTableID");

                    b.ToTable("waiterrequests", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.AnalyticsSnapshot", b =>
                {
                    b.Property<int>("SnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("snapshotid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SnapshotID"));

                    b.Property<decimal>("AverageOrderValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("averageordervalue");

                    b.Property<int>("CancelledOrders")
                        .HasColumnType("integer")
                        .HasColumnName("cancelledorders");

                    b.Property<decimal>("CustomerSatisfactionScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("customersatisfactionscore");

                    b.Property<int>("DailyOrders")
                        .HasColumnType("integer")
                        .HasColumnName("dailyorders");

                    b.Property<decimal>("DailyRevenue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("dailyrevenue");

                    b.Property<decimal>("FoodCostPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("foodcostpercentage");

                    b.Property<decimal>("InventoryValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("inventoryvalue");

                    b.Property<decimal>("LaborCostPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("laborcostpercentage");

                    b.Property<int>("LowStockItems")
                        .HasColumnType("integer")
                        .HasColumnName("lowstockitems");

                    b.Property<int>("NewCustomers")
                        .HasColumnType("integer")
                        .HasColumnName("newcustomers");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("ReturningCustomers")
                        .HasColumnType("integer")
                        .HasColumnName("returningcustomers");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshotdate");

                    b.Property<decimal>("TableTurnoverRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tableturnoverrate");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperature");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weathercondition");

                    b.Property<decimal>("WeatherImpactScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weatherimpactscore");

                    b.HasKey("SnapshotID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("analyticssnapshots", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budgetid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetID"));

                    b.Property<decimal>("ActualSpent")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("actualspent");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monthlybudget");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("BudgetID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.CompetitiveAnalysis", b =>
                {
                    b.Property<int>("AnalysisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("analysisid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalysisID"));

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("date")
                        .HasColumnName("analysisdate");

                    b.Property<decimal>("CompetitorAvgPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("competitoravgprice");

                    b.Property<string>("CompetitorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competitorname");

                    b.Property<decimal>("CompetitorRating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("competitorrating");

                    b.Property<string>("CompetitorStrengths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competitorstrengths");

                    b.Property<string>("CompetitorWeaknesses")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competitorweaknesses");

                    b.Property<decimal>("MarketShare")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("marketshare");

                    b.Property<decimal>("PriceCompetitiveness")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pricecompetitiveness");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("AnalysisID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("competitiveanalyses", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Allergies")
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FirstVisit")
                        .HasColumnType("timestamptz")
                        .HasColumnName("firstvisit");

                    b.Property<bool>("IsVIP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isvip");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lastvisit");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("loyaltypoints");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Preferences")
                        .HasColumnType("text")
                        .HasColumnName("preferences");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totalspent");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("integer")
                        .HasColumnName("totalvisits");

                    b.HasKey("CustomerID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.CustomerFeedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("feedbackid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isresolved");

                    b.Property<int?>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("ResolutionNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolutionnotes");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("FeedbackID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OrderID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("customerfeedbacks", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expenseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approvedby");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expensedate");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isrecurring");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiptnumber");

                    b.Property<string>("RecurringFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurringfrequency");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vendor");

                    b.HasKey("ExpenseID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.LoyaltyProgram", b =>
                {
                    b.Property<int>("LoyaltyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("loyaltyid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoyaltyID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<decimal>("DiscountPerPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.01m)
                        .HasColumnName("discountperpoint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int>("PointsForFreeItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("pointsforfreeitem");

                    b.Property<decimal>("PointsPerDollar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("pointsperdollar");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("programname");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("LoyaltyID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("loyaltyprograms", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.PredictiveData", b =>
                {
                    b.Property<int>("PredictionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("predictionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionID"));

                    b.Property<decimal>("ConfidenceLevel")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confidencelevel");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("generatedat");

                    b.Property<string>("PeakHours")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peakhours");

                    b.Property<int>("PredictedCustomers")
                        .HasColumnType("integer")
                        .HasColumnName("predictedcustomers");

                    b.Property<int>("PredictedOrders")
                        .HasColumnType("integer")
                        .HasColumnName("predictedorders");

                    b.Property<decimal>("PredictedRevenue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("predictedrevenue");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("date")
                        .HasColumnName("predictiondate");

                    b.Property<string>("RecommendedStaffing")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendedstaffing");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.HasKey("PredictionID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("predictivedata", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reservationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("createdat");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customeremail");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customername");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customerphone");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer")
                        .HasColumnName("partysize");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reservationtime");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("RestaurantTableID")
                        .HasColumnType("integer")
                        .HasColumnName("restauranttableid");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialrequests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Confirmed")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updatedat");

                    b.HasKey("ReservationID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("RestaurantTableID");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staffid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("hiredate");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("hourlyrate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("StaffID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.StaffPerformance", b =>
                {
                    b.Property<int>("PerformanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("performanceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceID"));

                    b.Property<decimal>("AverageOrderValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("averageordervalue");

                    b.Property<decimal>("EfficiencyScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("efficiencyscore");

                    b.Property<int>("NegativeReviews")
                        .HasColumnType("integer")
                        .HasColumnName("negativereviews");

                    b.Property<int>("OrdersServed")
                        .HasColumnType("integer")
                        .HasColumnName("ordersserved");

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("date")
                        .HasColumnName("performancedate");

                    b.Property<int>("PositiveReviews")
                        .HasColumnType("integer")
                        .HasColumnName("positivereviews");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("StaffID")
                        .HasColumnType("integer")
                        .HasColumnName("staffid");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totalsales");

                    b.HasKey("PerformanceID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("StaffID");

                    b.ToTable("staffperformances", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.StaffShift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shiftid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftID"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("endtime");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("hoursworked");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("iscompleted");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shiftdate");

                    b.Property<int>("StaffID")
                        .HasColumnType("integer")
                        .HasColumnName("staffid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("starttime");

                    b.HasKey("ShiftID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("StaffID");

                    b.ToTable("staffshifts", (string)null);
                });

            modelBuilder.Entity("Restaurant_System.Models.TableManagement", b =>
                {
                    b.Property<int>("TableManagementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tablemanagementid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableManagementID"));

                    b.Property<int?>("CurrentOrderID")
                        .HasColumnType("integer")
                        .HasColumnName("currentorderid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lastupdated");

                    b.Property<DateTime?>("OccupiedSince")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occupiedsince");

                    b.Property<DateTime?>("ReservationTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reservationtime");

                    b.Property<int?>("ReservedByCustomerID")
                        .HasColumnType("integer")
                        .HasColumnName("reservedbycustomerid");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("integer")
                        .HasColumnName("restaurantid");

                    b.Property<int>("RestaurantTableID")
                        .HasColumnType("integer")
                        .HasColumnName("restauranttableid");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seatingcapacity");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("SpecialFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialfeatures");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("XPosition")
                        .HasColumnType("integer")
                        .HasColumnName("xposition");

                    b.Property<int>("YPosition")
                        .HasColumnType("integer")
                        .HasColumnName("yposition");

                    b.HasKey("TableManagementID");

                    b.HasIndex("CurrentOrderID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("RestaurantTableID");

                    b.ToTable("tablemanagement", (string)null);
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("CustomizationOption", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Product", "Product")
                        .WithMany("CustomizationOptions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("KitchenNotification", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.InventoryItem", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Offer", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Order", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Offer", "AppliedOffer")
                        .WithMany()
                        .HasForeignKey("AppliedOfferID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Restaurant_System.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.RestaurantTable", "RestaurantTable")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantTableID");

                    b.HasOne("Restaurant_Menu.Models.User", "Waiter")
                        .WithMany("AssignedOrders")
                        .HasForeignKey("WaiterUserID");

                    b.Navigation("AppliedOffer");

                    b.Navigation("Restaurant");

                    b.Navigation("RestaurantTable");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderChangeHistory", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderItem", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderItemCustomization", b =>
                {
                    b.HasOne("CustomizationOption", "CustomizationOption")
                        .WithMany()
                        .HasForeignKey("CustomizationOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.OrderItem", "OrderItem")
                        .WithMany("Customizations")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomizationOption");

                    b.Navigation("OrderItem");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Payment", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryID");

                    b.Navigation("Category");

                    b.Navigation("Restaurant");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.ProductRecipe", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.RestaurantTable", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Review", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.StockTransaction", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.SubCategory", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.User", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.WaiterNotification", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.WaiterRequest", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.RestaurantTable", null)
                        .WithMany()
                        .HasForeignKey("RestaurantTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.AnalyticsSnapshot", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.Budget", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.CompetitiveAnalysis", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.Customer", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.CustomerFeedback", b =>
                {
                    b.HasOne("Restaurant_System.Models.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.Expense", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.LoyaltyProgram", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.PredictiveData", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.Reservation", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.RestaurantTable", "RestaurantTable")
                        .WithMany()
                        .HasForeignKey("RestaurantTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("Restaurant_System.Models.Staff", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Restaurant_System.Models.StaffPerformance", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_System.Models.Staff", "Staff")
                        .WithMany("Performances")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Restaurant_System.Models.StaffShift", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_System.Models.Staff", "Staff")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Restaurant_System.Models.TableManagement", b =>
                {
                    b.HasOne("Restaurant_Menu.Models.Order", "CurrentOrder")
                        .WithMany()
                        .HasForeignKey("CurrentOrderID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Restaurant_Menu.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant_Menu.Models.RestaurantTable", "RestaurantTable")
                        .WithMany()
                        .HasForeignKey("RestaurantTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentOrder");

                    b.Navigation("Restaurant");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.OrderItem", b =>
                {
                    b.Navigation("Customizations");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.Product", b =>
                {
                    b.Navigation("CustomizationOptions");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Restaurant_Menu.Models.User", b =>
                {
                    b.Navigation("AssignedOrders");
                });

            modelBuilder.Entity("Restaurant_System.Models.Customer", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant_System.Models.Staff", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
